language: python # Set the build language to Python

python: 3.6 # Set the version of Python to use

branches: master # Set the branch to build from

install:
    - pip install mkdocs # Install the required dependencies
    - pip install git+https://github.com/midnightprioriem/mkdocs-autolinks-plugin

script: true # Skip script (Don't use this if one already exists)

before_deploy:
    - mkdocs build --verbose --clean # Build a local version of the docs

deploy: # Deploy documentation to Github in the gh_pages branch
    provider: pages
    skip_cleanup: true
    github_token: 4c9a22502b032616804e7e8d6579bec5e22fe875
    local_dir: site
    on:
        branch: master
