
language: python
script:
  - pip install git+https://github.com/midnightprioriem/mkdocs-autolinks-plugin
  - pip install mkdocs-simple-plugin
  - pip install mkdocs
  - mkdocs build
  - git add site
  - git commit -m "building site"
  - git push
